  version: '3.7'
  services:
    config-server:
      image: franbusleiman/config-server
      ports:
        - "8888:8888"
      networks:
        - springcloud
      restart: always
    eureka-service:
      image: franbusleiman/eureka-service
      ports:
        - "8761:8761"
      networks:
        - springcloud
      restart: always
    oauth-service:
      image: franbusleiman/oauth-service
      ports:
        - "9100:9100"
      networks:
        - springcloud
      restart: always
      depends_on:
        - eureka-service
        - users-service
        - zipkin
    pets-service:
      image: franbusleiman/pets-service
      networks:
        - springcloud
      restart: always
      depends_on:
        - config-server
        - eureka-service
        - mysql
        - users-service
        - zipkin
     # env_file:
     #   - ../../chiflale/.env
    gateway-service:
      image: franbusleiman/gateway-service
      networks:
        - springcloud
      restart: always
      ports:
        - "1238:1238"
      depends_on:
        - eureka-service
        - users-service
        - pets-service
        - oauth-service
        - zipkin
    users-service:
      image: franbusleiman/users-service
      networks:
        - springcloud
      restart: always
      depends_on:
        - config-server
        - eureka-service
        - mysql
        - zipkin
    mysql:
      image: mysql
      ports:
        - "3306:3306"
      environment:
        MYSQL_ROOT_PASSWORD: sasa
        MYSQL_DATABASE: springboot_cloud
      networks:
        - springcloud
      restart: always
      volumes:
        - vmysql:/var/lib/mysql
    zipkin:
      image: openzipkin/zipkin
      ports:
        - "9411:9411"
      networks:
        - springcloud
      restart: always
  networks:
    springcloud:
      name: springcloud
  volumes:
    vmysql:
      name: vmysql


