  version: '3.7'
  services:
    eureka-service:
      image: eureka-service
      ports:
        - "8761:8761"
      networks:
        - springcloud
      restart: always
    oauth-service:
      image: oauth-service
      ports:
        - "9100:9100"
      networks:
        - springcloud
      restart: always
      depends_on:
        - eureka-service
        - users-service
        - animals-service
        - medicines-service
        - consultations-service
    gateway-service:
      image: gateway-service
      networks:
        - springcloud
      restart: always
      ports:
        - "8085:1238"
      depends_on:
        - eureka-service
        - users-service
        - animals-service
        - medicines-service
        - consultations-service
        - oauth-service
    users-service:
      image: users-service
      networks:
        - springcloud
      restart: always
      depends_on:
        - eureka-service
        - mysql
    migrator-service:
      image: migrator-service
      networks:
        - springcloud
      restart: always
      depends_on:
        - eureka-service
        - mysql
      volumes:
        - /home/ubuntu/liro/vetter:/liro/vetter
        - /home/ubuntu/liro/cpvet:/liro/cpvet
    animals-service:
      image: animals-service
      networks:
        - springcloud
      restart: always
      depends_on:
        - eureka-service
        - mysql
    medicines-service:
      image: medicines-service
      networks:
        - springcloud
      restart: always
      depends_on:
        - eureka-service
        - mysql
    clinics-service:
      image: clinics-service
      networks:
        - springcloud
      restart: always
      depends_on:
        - eureka-service
        - mysql
        - zipkin
    consultations-service:
      image: consultations-service
      networks:
        - springcloud
      restart: always
      depends_on:
        - eureka-service
        - mysql
        - zipkin
    mysql:
      image: mysql
      ports:
        - "3306:3306"
      environment:
        MYSQL_ROOT_PASSWORD: sasa
        MYSQL_DATABASE: springboot_cloud
      networks:
        - springcloud
      restart: always
      volumes:
        - volume_liro:/var/lib/mysql
  networks:
    springcloud:
      name: springcloud
  volumes:
    volume_liro:
      name: volume_liro


