version: '3.7'
services:
  config-server:
    image: config-server
    ports:
      - "8888:8888"
    networks:
      - springcloud
    restart: always
  eureka-service:
    image: eureka-service
    ports:
      - "8761:8761"
    networks:
      - springcloud
    restart: always
  oauth-service:
    image: oauth-service
    ports:
      - "9100:9100"
    networks:
      - springcloud
    restart: always
    depends_on:
      - eureka-service
      - users-service
      - animals-service
      - zipkin
  gateway-service:
    image: gateway-service
    networks:
      - springcloud
    restart: always
    ports:
      - "8085:1238"
    depends_on:
      - eureka-service
      - users-service
      - animals-service
      - oauth-service
      - zipkin
  users-service:
    image: users-service
    networks:
      - springcloud
    restart: always
    depends_on:
      - config-server
      - eureka-service
      - zipkin
  animals-service:
    image: animals-service
    networks:
      - springcloud
    restart: always
    depends_on:
      - config-server
      - eureka-service
      - zipkin

  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      - springcloud
    restart: always
networks:
  springcloud:
    name: springcloud

